export interface ArticleImage {
  src: string;
  alt: string;
  loading?: string;
  sizes?: string;
  srcset?: string;
}

export interface ArticleMetadata {
  slug: string;                     // URL slug: "x-bot-community-analytics-2025-01-16"
  product: string;                  // "X Bot"
  title: string;                    // "Advanced Community Analytics for Crypto Projects"
  subtitle: string;                 // Article subtitle (40-60 words)
  publishDate: string;              // ISO date: "2025-01-16T10:00:00Z"
  tweetId: string;                  // Source tweet ID
  featuredImage?: ArticleImage;     // Main article image
  seoDescription: string;           // Meta description (150-160 chars)
}

export const articles: ArticleMetadata[] = [
{
  slug: 'x-bot-2025-12-07',
  product: 'X Bot',
  title: 'X Bot: Verify Authentic Community Engagement with Official X API',
  subtitle: 'Crypto projects struggle to distinguish genuine community traction from manufactured hype generated by bot farms. X Bot solves this challenge by delivering verifiable engagement analytics through official X API integration, tracking KOL performance across 100+ accounts simultaneously while detecting inauthentic activity through sophisticated pattern analysis.',
  publishDate: '2025-12-07T10:03:06.719Z',
  tweetId: '',
  featuredImage: {
    src: '/assets/images/docs/x-bot/x-bot-0.png',
    alt: 'Product screenshot',
    loading: 'eager'
  },
  seoDescription: 'X Bot tracks authentic crypto community engagement using official X API. Monitor 100+ KOLs, detect bot farms, and measure real growth with verified analytics.'
},
{
  slug: 'blockchain-badges-2025-12-07',
  product: 'Blockchain Badges',
  title: 'Blockchain Badges: Issue Tamper-Proof Digital Credentials with Blockchain Verification',
  subtitle: 'Educational institutions and organizations struggle with credential fraud as paper certificates remain vulnerable to forgery. Blockchain Badges solves this challenge by creating immutable digital credentials with cryptographic verification, enabling instant authentication by employers while completely eliminating diploma fraud through blockchain certification.',
  publishDate: '2025-12-07T10:03:18.543Z',
  tweetId: '',
  featuredImage: {
    src: '/assets/images/docs/blockchain-badges/blockchain-badges-0.png',
    alt: 'Cover',
    loading: 'eager'
  },
  seoDescription: 'Issue tamper-proof digital credentials with Blockchain Badges. Immutable blockchain certification prevents fraud and enables instant verification by employers.'
},
{
  slug: 'esg-credits-2025-12-07',
  product: 'ESG Credits',
  title: 'ESG Credits: Blockchain Environmental Impact Reporting with ICMA Framework Support',
  subtitle: 'Financial institutions face mounting pressure to provide verifiable environmental impact reporting that prevents double-counting and meets regulatory frameworks. ESG Credits addresses this challenge by delivering blockchain-verified green asset reporting with ICMA framework compliance, enabling banks to integrate transparent sustainability metrics directly into customer applications.',
  publishDate: '2025-12-07T10:03:28.709Z',
  tweetId: '',
  featuredImage: {
    src: '/assets/images/marketplace/fallback/esg-credits/01-report.png',
    alt: 'ESG Credits solution',
    loading: 'eager'
  },
  seoDescription: 'ESG Credits delivers blockchain-verified environmental reporting for banks with ICMA compliance, double-counting prevention, and direct banking app integration.'
},
{
  slug: 'fan-game-cube-2025-12-07',
  product: 'Fan Game Cube',
  title: 'Fan Game Cube: Monetize Fan Engagement Through NFT Field Zones',
  subtitle: 'When the final whistle blows, fan engagement—and revenue—typically ends with it. Fan Game Cube transforms this dynamic by tokenizing field sections as NFTs, creating continuous monetization streams as fans earn points when real-time game events occur at their owned coordinates across football, chess, tennis, and cricket.',
  publishDate: '2025-12-07T10:03:39.761Z',
  tweetId: '',
  featuredImage: {
    src: '/assets/images/docs/fan-game-cube/fan-game-cube-0.png',
    alt: 'Product screenshot',
    loading: 'eager'
  },
  seoDescription: 'Fan Game Cube monetizes fan engagement through NFT field zones. Fans earn rewards when real match events occur at owned coordinates across multiple sports.'
}
];
